name: handysqaud_user_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: ZalandoSansSemiExpanded
      fonts:
        - asset: assets/fonts/ZalandoSansSemiExpanded-Light.ttf
          weight: 300      
        - asset: assets/fonts/ZalandoSansSemiExpanded-Regular.ttf
          weight: 400
        - asset: assets/fonts/ZalandoSansSemiExpanded-Medium.ttf
          weight: 500
        - asset: assets/fonts/ZalandoSansSemiExpanded-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/ZalandoSansSemiExpanded-Bold.ttf
          weight: 700
        - asset: assets/fonts/ZalandoSansSemiExpanded-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/ZalandoSansSemiExpanded-Black.ttf
          weight: 900          
  